spring:
  datasource:
    url: jdbc:postgresql://shivani-db.cn4k6qwks3p5.ap-south-1.rds.amazonaws.com:5432/shivani
    username: postgres
    password: Opffarmy007
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  
server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript,text/html,text/xml,text/plain
    min-response-size: 1024

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in ms
